name: &name thing
version: 0.0.0

dependencies: []

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: .

  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -O2

  dependencies:
  - *name

defaults: xnuk/xnuk@hpack
